apiVersion: v1
kind: Secret
metadata:
    name: nist2slack-secrets
data:
    SLACK_API_KEY: "BASE64_ENCODED_SLACK_API_KEY"
    CHANNEL_ID: "BASE64_ENCODED_CHANNEL_ID"
    IMAGE_URL: "BASE64_ENCODED_IMAGE_URL"
